### ISSUE TITLE
this isn't an issue with your software at all

### ISSUE THREAD

**Issue by trace7087** [alsyundawy/Parallels#12]
hey guys, I felt that people needed to know this so I thought I would add it here.

with the new update of parallels desktop 19.1/19.2 which parallels are quite aware of and can not be corrected currently with their new release they redirect you to back to 19.0 one.

you get an error 10 for mass usb when connecting to windows 11.

**Comment by trueToastedCode** [comment]
I didn't know 19.2 exists already 😃
