### ISSUE TITLE
What's the error?Is this has been banned?

### ISSUE THREAD

**Issue by ChaNg1o1** [alsyundawy/Parallels#13]
11-16 09:26:25.410 F /vm:37391:bbbc9/ Vm args '/Applications/Parallels Desktop.app/Contents/MacOS//Parallels VM.app/Contents/MacOS/prl_vm_app' '--vm-name' 'Kali Linux' '--uuid' '{eebe6f9a-fdb0-4bf6-94e4-b079919fb7a0}' '--dir-uuid' '{8caa6079-9174-4c0f-90fb-9c1bfee141b9}' '--log-dir' '/Users/chang1o/Parallels/Kali Linux.pvm'
11-16 09:26:25.410 F /prldirs:37391:bbbc9/ ParallelsDirs::Init( ) was called. Current app mode = 1 ( DESKTOP ) build version: 19.1.0 (54729) Sat, 14 Oct 2023 10:12:17
11-16 09:26:25.410 F /vm:37391:bbbc9/ Parallels Virtual Machine Constructed
11-16 09:26:25.415 W /vm:37391:bbbc9/ Validating peer PID
11-16 09:26:25.416 F /vm:37391:bbbc9/ Failed to validate peer
11-16 09:26:25.416 F /vm:37391:bbbc9/ Connection to dispatcher failed!
11-16 09:26:25.416 F /vm:37391:bbbc9/ ***** VM process exiting with code -2
<img width="1333" alt="Screenshot 2023-11-16 at 09 31 20" src="https://github.com/alsyundawy/Parallels/assets/127028518/d51d4d1d-b893-4586-8d65-fd0b2a0c15c7">

**Comment by trueToastedCode** [comment]
Unable to reproduce... But this (very likely) means, that the core hook or the replacement instructions have failed. You should check it's logs in the console. It had the prefix [bad_prl_disp_service]
