### ISSUE TITLE
Any suggestion for the xcode error

### ISSUE THREAD

**Issue by ruscito** [alsyundawy/Parallels#16]
Hello when I run the install.sh I get the following error

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

Any suggetions

Thanks

**Comment by ruscito** [comment]
never mind found the issue

**Comment by xRiddin** [comment]
what was the issue? im facing the same issue?

**Comment by xRiddin** [comment]
yes nvm found the solution

**Comment by ChesterYue** [comment]
https://github.com/nodejs/node-gyp/issues/569#issuecomment-94917337
