### ISSUE TITLE
HELP! "Parallels Tools must be updated"

### ISSUE THREAD

**Issue by RigHakiko** [alsyundawy/Parallels#31]
![Pasted_Image_2023_12_18__9_46](https://github.com/alsyundawy/Parallels/assets/17807588/62779097-b7ff-454c-b11a-bb1f7c370c67)
 
I crack parallels today, this appears everytime I start a Windows VM.
Windows VM will loop restart if I do nothing.

**Comment by yashrastogi** [comment]
I think it's because they are using an older version of parallels VM binary and there's some mismatch in parallel tools version that causes this.

**Comment by LucasBonafe** [comment]
@yashrastogi, and how to fix?

Same problem here, downgraded today from 19.2...

**Comment by trueToastedCode** [comment]
Duplication of https://github.com/trueToastedCode/ParallelsLab/issues/33
